package com.examly.springapp.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

//The class uses Lombok annotations (@Getter and @Setter) to automatically generate getter and setter methods for all fields, reducing boilerplate code.
@Getter
@Setter

//The class provides both a default constructor and a parameterized constructor, allowing objects to be created with or without values for the fields.
@AllArgsConstructor
@NoArgsConstructor

// @Entity annotation is used to mark the class as a JPA entity, meaning that objects of this class will be persisted to a database table.
@Entity

public class AppointmentInfo {
    @Id //@Id annotation marks the appointmentId field as the primary key of the entity.

    // /The @GeneratedValue annotation with GenerationType.IDENTITY strategy indicates that the primary
    // key value will be automatically generated by the database (usually using auto-increment)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long appointmentId;
    private long userId;
    private long serviceCenterId;
    private String productName;
    private String purchaseDate;
    private String productModelNo;
    private String problemStatement;
    private String bookingDate;
    private String bookingTime;
    private String userName;
    private String centerName;
    private String paymentDone;
}
